version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers: [ SkYNewZ ]
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        dependency-type: production

  - package-ecosystem: "gomod"
    directory: "/"
    reviewers: [ SkYNewZ ]
    schedule:
      interval: "weekly"
    groups:
      go:
        dependency-type: production
